version: '3.8'

services:
  frontend:
    container_name: stock-trader-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./client/nginx.local.conf:/etc/nginx/conf.d/default.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
