version: '3.8'

services:
  backend:
    container_name: stock-trader-backend
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      # Using host.docker.internal to connect to local PostgreSQL
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_NAME=stock_trader
      - DB_USER=postgres
      - DB_PASSWORD=1215
      - JWT_SECRET=your-super-secret-jwt-key-for-stock-trader
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    networks:
      - app-network

  frontend:
    container_name: stock-trader-frontend
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_API_URL=/api
    volumes:
      - ./client/nginx.local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
